version: 2.1

executors: &executors
  bats:
    docker:
      - image: circleci/buildpack-deps:stretch-curl
    working_directory: ~/github-actions-toolkit

commands: &commands
  install_bats:
    parameters:
      version:
        default: v1.1.0
        type: string
    steps:
      - run:
          command: |
            git clone -b << parameters.version >> https://github.com/bats-core/bats-core.git

            cd bats-core
            sudo ./install.sh /usr/local || ./install.sh /usr/local
            cd ..
            rm -rf bats-core
          name: install BATS
orbs:
  shellcheck: circleci/shellcheck@1.3.14
  bats:
    commands: *commands
    executors: *executors
    jobs:
      test_all:
        executor: bats
        steps:
          - checkout
          - install_bats
          - run: bats -r test

workflows:
  version: 2
  on_commit:
    jobs:
      - bats/test_all
      - shellcheck/check:
          exclude: (bin|test)/*
