name: Examples for those who want to exclude some branches/tags

on: 
  push

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
      with:
        fetch-depth: 1
    - uses: ./actions/transform-ref
      id: tranform-ref
