name: testing for set_env

on: 
  push

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
      with:
        fetch-depth: 1
    - name: Copy toolkit.sh and Dockerfile
      run: cp toolkit.sh actions/Dockerfile actions/set_env/
    - uses: ./actions/set_env
      id: set_env
    - name: See environments
      run: echo "$foo1 / $foo2"
