name: testing for toggle_commands

on: 
  push

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
      with:
        fetch-depth: 1
    - name: Copy toolkit.sh and Dockerfile
      run: cp toolkit.sh actions/Dockerfile actions/toggle_commands/
    - uses: ./actions/toggle_commands
      id: toggle_commands
